apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  labels:
    name: {{ .Chart.Name }}-service
    app: {{ .Chart.Name }}
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: {{ .Chart.Name }}-pod
    app: springboot-devops
    component: database