apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  labels:
    name: {{ .Chart.Name }}-service
    app: springboot-devops
    component: springboot-app
spec:
  ports:
    - port: {{ .Values.springbootPort }}
      targetPort: {{ .Values.springbootPort }}
  selector:
    name: {{ .Chart.Name }}-pod
    app: springboot-devops
    component: springboot-app
