apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  labels:
    name: {{ .Chart.Name }}-service
    app: springboot-devops
    component: springboot-app
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: {{ .Chart.Name }}-pod
    app: springboot-devops
    component: springboot-app
