apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  labels:
    name: {{ .Chart.Name }}-service
    app: {{ .Chart.Name }}
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30800
  selector:
    name: {{ .Chart.Name }}-pod
    app: springboot-devops
    component: springboot-app
