apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  labels:
    name: {{ .Chart.Name }}-service
    app: {{ .Chart.Name }}
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30300
  selector:
    name: {{ .Chart.Name }}-pod
    app: springboot-devops
    component: react-app
    
