name: Build and Push Docker Images

on: 
  workflow_dispatch:
    inputs:
      buildReactDockerImage:
        description: 'Build New React Docker Image'
        required: false
        type: boolean
      reactDockerTag:
        description: 'React Docker Tag'
        required: true
        default: 'latest'
        type: string
      buildSpringbootDockerImage:
        description: 'Build New Springboot Docker Image'
        required: false
        type: boolean
      springbootDockerTag:
        description: 'Spring Boot Docker Tag'
        required: true
        default: 'latest'
        type: string

  workflow_call:
    inputs:
      buildReactDockerImage:
        required: false
        type: boolean
      reactDockerTag:
        required: true
        default: 'latest'
        type: string
      buildSpringbootDockerImage:
        required: false
        type: boolean
      springbootDockerTag:
        required: true
        default: 'latest'
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push React Image
      if: ${{ inputs.buildReactDockerImage == true }}
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/springboot-devops_react:${{ inputs.reactDockerTag }} ./react-app
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/springboot-devops_react:${{ inputs.reactDockerTag }}

    - name: Build and Push Spring Boot Image
      if: ${{ inputs.buildSpringbootDockerImage == true }}
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/springboot-devops_springboot:${{ inputs.springbootDockerTag }} ./springboot
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/springboot-devops_springboot:${{ inputs.springbootDockerTag }}