name: Build and Push Latest Spring Boot Image

on: 
  push:
    branches: [main]
    paths:
      - springboot/**

jobs:
  call-push-docker-images:
    name: Build and Push Latest Spring Boot Image
    uses: dobsondev/springboot-devops/.github/workflows/cd-build-and-push.yml@main
    with:
      buildReactDockerImage: false
      reactDockerTag: latest
      buildSpringbootDockerImage: true
      springbootDockerTag: latest
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}