name: Build and Push Latest React Image

on: 
  push:
    branches: [main]
    paths:
      - react-app/**

jobs:
  call-push-docker-images:
    name: Build and Push Latest React Image
    uses: dobsondev/springboot-devops/.github/workflows/cd-build-and-push.yml@main
    with:
      buildReactDockerImage: true
      reactDockerTag: latest
      buildSpringbootDockerImage: false
      springbootDockerTag: latest
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}