name: Auto Push Latest React Docker Image to DockerHub

on: 
  push:
    branches: [main]
    paths:
      - react-app/**

env:
  REACT_TAG: latest

jobs:
  call-push-docker-images:
    name: Call Push Docker Images Workflow for Latest React Image
    uses: dobsondev/springboot-devops/.github/workflows/push-docker-images.yml@main
    with:
      buildReactDockerImage: true
      reactDockerTag: REACT_TAG
      buildSpringbootDockerImage: false
      springbootDockerTag: REACT_TAG
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}