name: Auto Push Spring Boot Docker Image to DockerHub

on: 
  push:
    branches: [main]
    paths:
      - springboot/**

env:
  SPRINGBOOT_TAG: v0.1

jobs:
  call-push-docker-images:
    uses: dobsondev/springboot-devops/.github/workflows/push-docker-images.yml@main
    with:
      buildReactDockerImage: false
      reactDockerTag: SPRINGBOOT_TAG
      buildSpringbootDockerImage: true
      springbootDockerTag: SPRINGBOOT_TAG