name: Auto Push React Docker Image to DockerHub

on: 
  push:
    branches: [main]
    paths:
      - react-app/**

env:
  REACT_TAG: v0.1

jobs:
  call-push-docker-images:
    uses: dobsondev/springboot-devops/.github/workflows/push-docker-images.yml@main
    with:
      buildReactDockerImage: true
      reactDockerTag: REACT_TAG
      buildSpringbootDockerImage: false
      springbootDockerTag: REACT_TAG