name: Auto Push React Docker Image to DockerHub

on: 
  push:
    branches: [main]
    paths:
      - react-app/**

env:
  REACT_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/springboot-devops_react:v0.1

jobs:
  build:
    name: Create and Push React Docker Image to DockerHub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build React Docker Image and Push to DockerHub
      uses: docker/build-push-action@v5
      with:
        context: ./react-app
        push: true
        tags: ${{ env.REACT_TAG }}