name: Build and Push Release Docker Images

on:
  release:
    types: [published]

jobs:
  call-push-docker-images:
    name: Build and Push Release Docker Images
    uses: dobsondev/springboot-devops/.github/workflows/cd-build-and-push.yml@main
    with:
      buildReactDockerImage: true
      reactDockerTag: ${{ github.event.release.tag_name }}
      buildSpringbootDockerImage: true
      springbootDockerTag: ${{ github.event.release.tag_name }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}