name: Push Release Docker Images to DockerHub

on:
  release:
    types: [published]

jobs:
  call-push-docker-images:
    name: Call Push Docker Images Workflow for Release Images
    uses: dobsondev/springboot-devops/.github/workflows/push-docker-images.yml@main
    with:
      buildReactDockerImage: true
      reactDockerTag: ${{ github.event.release.tag_name }}
      buildSpringbootDockerImage: true
      springbootDockerTag: ${{ github.event.release.tag_name }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}