name: Continuous Integration

on:
  pull_request:
    branches: [ "main" ]

env:
  REACT_TEST_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/springboot-devops_react:test
  SPRINGBOOT_TEST_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/springboot-devops_springboot:test

jobs:
  dockerhub_login_check:
    name: Test Building Docker Images
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

  build_react_docker_image:
    name: Test Building React Docker Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Test Building React Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./react-app
        load: true
        tags: ${{ env.REACT_TEST_TAG }}

  build_springboot_docker_image:
    name: Test Building Springboot Docker Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Test Building Springboot Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./springboot
        load: true
        tags: ${{ env.SPRINGBOOT_TEST_TAG }}