name: Continuous Integration

on:
  pull_request:
    branches: [ "main" ]

env:
  REACT_TEST_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/springboot-devops_react:test
  SPRINGBOOT_TEST_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/springboot-devops_springboot:test

jobs:
  dockerhub_login_check:
    name: Test DockerHub Login
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

  build_react_docker_image:
    name: Test Building React Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Test React Image
      uses: docker/build-push-action@v5
      with:
        context: ./react-app
        platforms: linux/amd64,linux/arm64,linux/arm64/v8
        tags: ${{ env.REACT_TEST_IMAGE }}

  build_springboot_docker_image:
    name: Test Building Spring Boot Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Test Building Springboot Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./springboot
        platforms: linux/amd64,linux/arm64,linux/arm64/v8
        tags: ${{ env.SPRINGBOOT_TEST_TAG }}