name: Push Docker Images to DockerHub

on: 
  workflow_dispatch:
    inputs:
      buildReactDockerImage:
        description: 'Build New React Docker Image'
        required: false
        type: boolean
      reactDockerTag:
        description: 'React Docker Tag'
        required: true
        default: 'v0.1'
        type: string
      buildSpringbootDockerImage:
        description: 'Build New Springboot Docker Image'
        required: false
        type: boolean
      springbootDockerTag:
        description: 'Spring Boot Docker Tag'
        required: true
        default: 'v0.1'
        type: string

jobs:
  build:
    name: Create and Push Docker Images to DockerHub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build React Docker Image and Push to DockerHub
      if: ${{ inputs.buildReactDockerImage == true }}
      uses: docker/build-push-action@v5
      with:
        context: ./react-app
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/springboot-devops_react:${{ inputs.reactDockerTag }}

    - name: Build Spring Boot Docker Image and Push to DockerHub
      if: ${{ inputs.buildSpringbootDockerImage == true }}
      uses: docker/build-push-action@v5
      with:
        context: ./springboot
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/springboot-devops_springboot:${{ inputs.springbootDockerTag }}